### ISSUE TITLE
MSDN_Crawler issue

### ISSUE THREAD

**Issue by Klefo0** [fireeye/flare-ida#101]
I stumble on this error, but in .py file, I don't find any kind of that string appear in source code, can you review it for me, please?
![Screenshot 2021-01-05 194022](https://user-images.githubusercontent.com/70630854/103654525-92b6aa00-4f98-11eb-8145-4ab201f6a856.png)

**Comment by mr-tz** [comment]
This could be a syntax error. Try running `MSDN_crawler/msdn_crawler.py <path to extracted MSDN documentation> <path to tilib.exe> <path to til files>`.

Alternatively, you can use the extracted information available here: https://github.com/mr-tz/flare-ida/blob/master/MSDN_data/msdn_data.zip.

Please reopen this issue if you need further support.

**Comment by Klefo0** [comment]
I have tried it again, nothing change.

**Comment by mr-tz** [comment]
Have you tried the annotator plugin with the `msdn_data` file I linked above?

**Comment by Klefo0** [comment]
Yes

**Comment by mr-tz** [comment]
What output do you get?

**Comment by Klefo0** [comment]
I saw the warning same as one in the pic I uploaded first

**Comment by mr-tz** [comment]
What steps are you taking to run the plugin?

**Comment by Klefo0** [comment]
First I opened command prompt in flare plugin's folder, then I typed: "<python2 folder/python>" <path to extracted MSDN documentation> <path to tilib.exe> <path to til files>

**Comment by Klefo0** [comment]
Um.., I tried again then it happen like this
![Uploading Screenshot 2021-01-07 212157.png…]()

**Comment by mr-tz** [comment]
Try to follow the steps under "Running the MSDN annotations plug-in" from https://www.fireeye.com/blog/threat-research/2014/09/flare-ida-pro-script-series-msdn-annotations-ida-pro-for-malware-analysis.html using the provided XML (ZIP).

**Comment by Klefo0** [comment]
i've follow it step-by-step, it stucks right there

**Comment by mr-tz** [comment]
It looks like you're running the "Preparing the MSDN database file" steps. When using the parsed XML those can be skipped and you can hop straight into IDA.

**Comment by Klefo0** [comment]
Ok, thank for helping me.

**Comment by mr-tz** [comment]
You're welcome. Let me know if there's anything else I can help with.
