### ISSUE TITLE
MSDN_Crawler: many tilib.exe errors

### ISSUE THREAD

**Issue by williballenthin** [fireeye/flare-ida#3]
as reported by @wzr in #2.

> In the meantime I have included a `try: except: block` around
> 
> ```
>    if file.endswith('htm'):
>         file_counter += 1
>         try:
>             result = parse_file(os.path.join(root, file), const_enum)
>         except:
>             error_files.append(file)
>         if result:
>             results.append(result)
>     print 'ERROR processing %d files' % len(error_files)
> ```
> 
> Which resulted in:
> 
> ```
> ERROR processing 21828 files
> Parsed 329993 files
> Extracted information about 15263 functions
> ```
> 
> Does this correspond with your numbers?

**Comment by flypuma** [comment]
It's still not work,although i change the py file

**Comment by niklaus520** [comment]
@flypuma can u paste the error infos in ur post?

**Comment by flypuma** [comment]
@niklaus520 

Traceback (most recent call last):
  File "C:\flare-ida-master\MSDN_crawler\msdn_crawler.py", line 414, in <module>

    main()
  File "C:\flare-ida-master\MSDN_crawler\msdn_crawler.py", line 399, in main
    (file_counter, results) = parse_files(msdn_directory, tilib_exe, til_dir)
  File "C:\flare-ida-master\MSDN_crawler\msdn_crawler.py", line 372, in parse_fi
les
    result = parse_file(os.path.join(root, file), const_enum)
  File "C:\flare-ida-master\MSDN_crawler\msdn_crawler.py", line 277, in parse_fi
le
    return parse_new_style(file, content, const_enum)
  File "C:\flare-ida-master\MSDN_crawler\msdn_crawler.py", line 185, in parse_ne
w_style
    constant_descriptions.append(strip_html(string.text.encode('ascii')).encode(
'utf-8'))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 64:
 ordinal not in range(128)

**Comment by niklaus520** [comment]
which line have u changed? How many files caught error while processing?

**Comment by niklaus520** [comment]
@flypuma which line have u changed? How many files caught error while processing?

**Comment by flypuma** [comment]
@niklaus520  just line you pasted, it begins from line 176. If I do not chang these lines, It has the issue just like #2. I didn't show the number

**Comment by flypuma** [comment]
@niklaus520  I run the original msdn-crawler.py and txtracted about 33984 functions, just colse to yours. How could i get the file in you blog site.

**Comment by niklaus520** [comment]
@flypuma `http://blog.depressedmarvin.com/upload/2015/02/09/msdn_data_nn.xml`

you can just `wget` it

**Comment by flypuma** [comment]
@niklaus520  Thanks a lot. Could you upload the file msdn_crawler.py?

**Comment by niklaus520** [comment]
http://blog.depressedmarvin.com/ <http://blog.depressedmarvin.com/upload/2015/02/10/msdn_crawler.py> upload/2015/02/10/msdn_crawler.py

 

well, now u can try my script, see if there are still errors.

 

Then u can compare them, maybe some lines are different~

 

发件人: flypuma [mailto:notifications@github.com] 
发送时间: 2015年2月10日 13:30
收件人: fireeye/flare-ida
抄送: Marvin
主题: Re: [flare-ida] MSDN_Crawler: many tilib.exe errors (#3)

 

@niklaus520 <https://github.com/niklaus520>  Thanks a lot. Could you upload the file msdn_crawler.py?

**Comment by thansau239** [comment]
i got the issue when run python script annotate_IDB_MSDN, please help me

Traceback (most recent call last):
File "C:/Program Files/IDAPro6.6/python/flare/annotate_IDB_MSDN.py", line 117, in on_ok_button
IDB_MSDN_Annotator.main(config)
File "C:/Program Files/IDAPro6.6/python/flare\IDB_MSDN_Annotator__init__.py", line 523, in main
functions_map = parse_xml_data_files(msdn_data_dir)
File "C:/Program Files/IDAPro6.6/python/flare\IDB_MSDN_Annotator__init__.py", line 486, in parse_xml_data_files
additional_functions = xml_parser.parse(xml_file)
File "C:/Program Files/IDAPro6.6/python/flare\IDB_MSDN_Annotator\xml_parser.py", line 283, in parse
parser.parse(xmlfile)
File "C:\Program Files\IDAPro6.6\lib\xml\sax\expatreader.py", line 107, in parse
xmlreader.IncrementalParser.parse(self, source)
File "C:\Program Files\IDAPro6.6\lib\xml\sax\xmlreader.py", line 123, in parse
self.feed(buffer)
File "C:\Program Files\IDAPro6.6\lib\xml\sax\expatreader.py", line 211, in feed
self._err_handler.fatalError(exc)
File "C:\Program Files\IDAPro6.6\lib\xml\sax\handler.py", line 38, in fatalError
raise exception
xml.sax._exceptions.SAXParseException: C:\Program Files\IDAPro6.6\python\flare\annotate_IDB_MSDN.py:1:2: not well-formed (invalid token)

Thank you very much!

**Comment by I-VANN** [comment]
to niklaus520
if you change this instruction you can eliminate all error related to unicode:
                    for string in parsed_html.findAll(width='60%'):
                        try:
                            constant_descriptions.append(strip_html(string.text.encode('ascii')).encode('utf-8'))
                        except Exception,e:
                            constant_descriptions.append(strip_html(string.text.encode('utf-8')))

please upload to your code so all can download it.

Ivan

**Comment by niklaus520** [comment]
@I-VANN Here is the code: http://blog.depressedmarvin.com/upload/2015/02/10/msdn_crawler.py && here is the data file: http://blog.depressedmarvin.com/upload/2015/02/09/msdn_data_nn.xml

**Comment by I-VANN** [comment]
I've just modified the file with my suggestion, it was only for other people.
So if you think that this change to your modified file is acceptable you can modify for all.
Thank you for your availability.

**Comment by niklaus520** [comment]
@I-VANN cool, thanks for your suggestion

**Comment by mr-tz** [comment]
Closing this old issue. Please check if the following file works for you after unzipping it.
https://github.com/mr-tz/flare-ida/blob/master/MSDN_data/msdn_data.zip
Please reopen this issue if you need further assistance.
