### ISSUE TITLE
Callee Plugin Missing Some Arguments?

### ISSUE THREAD

**Issue by keithjjones** [fireeye/flare-ida#45]
I noticed this using the Callee plugin today:

![image](https://cloud.githubusercontent.com/assets/5360855/24074329/d9f48198-0bdc-11e7-8121-7113a9fc3c4a.png)

The push 1Ch isn't identified as the third argument to the function.  Is it perhaps an issue with the lea between the instructions?

I applied the VirtualQuery signature by selecting the call, pressing Alt-J, and using the global function VirtualQuery.

**Comment by jhsmith** [comment]
There is already a  comment for line 414129 ("size of buffer on stack") on the line with the jump target label "loc_414129". So deleting that manual comment will likely allow IDA's stack argument label to be seen. I'm not sure if you'll need to manually re-run the apply callee type plugin again to force it to appear.

**Comment by keithjjones** [comment]
Oh good point, I didn't notice that.  Thanks!

(You do have to run it again, but that's no big deal.)
