### ISSUE TITLE
Installing on Mac OSX

### ISSUE THREAD

**Issue by securisec** [fireeye/flare-ida#51]
Any instructions on how to install on OSX? I tried following the general directions for the windows installation, but cant import either the plugins or vivisect, nor run any of them.
This is on ida 7.0
Thanks!

**Comment by jhsmith** [comment]
It should be nearly the same process as described for Windows. Have you previously tried these plugins with IDA prior to 7.0? We haven't yet gotten a chance to update our plugins for the API changes introduced in IDA 7.0 (https://github.com/fireeye/flare-ida/issues/50).

**Comment by securisec** [comment]
Thanks @jhsmith it looks like according to hexrays, all these plugins have to be ported to 7.0 in order for them to be compatible. Look forward to you guys porting it over! thanks!

**Comment by securisec** [comment]
Perhaps you can give me a second pointer. I was able to get an older version of ida where i can successfully detect flare-ida plugins, but when i try to load them, i am getting an import error on vivisect. I have tried installing vivisect both using pip from git master, and have cloned vivisect and added it to python path but ida doesnt seem to recognize it. 

Thanks!
