### ISSUE TITLE
MSDN Annotations standalone

### ISSUE THREAD

**Issue by confilemg** [fireeye/flare-ida#63]
Which files do I need in order to let "MSDN Annotations" run standalone without the other plugins?

**Comment by mr-tz** [comment]
Once you have the MSDN database file (e.g. from https://github.com/mr-tz/flare-ida/blob/master/MSDN_data/msdn_data.zip) you need:
- flare-ida\python\flare\annotate_IDB_MSDN.py
- the files in flare-ida\python\flare\IDB_MSDN_Annotator
