### ISSUE TITLE
_TOKEN_INFORMATION_CLASS: failed to add constant

### ISSUE THREAD

**Issue by confilemg** [fireeye/flare-ida#64]
When I run the script I get the following error: 

_TOKEN_INFORMATION_CLASS: failed to add constant TokenUser=1 (0x1)
_TOKEN_INFORMATION_CLASS: failed to add constant TokenGroups=2 (0x2)
_TOKEN_INFORMATION_CLASS: failed to add constant TokenPrivileges=3 (0x3)
_TOKEN_INFORMATION_CLASS: failed to add constant TokenOwner=4 (0x4)

**Comment by mr-tz** [comment]
Which script are you running? Is there any additional output?

**Comment by confilemg** [comment]
I am running MSDN Annotations

**Comment by mr-tz** [comment]
I am not sure that the MSDN plugin generates this output. It might stem from IDA. Can you provide additional context?
